stages:
  - security
  - notify
  - test

gitleaks_scan:
  stage: security
  image: zricethezav/gitleaks:v8.30.0
  variables:
    GIT_DEPTH: 0
  script:
    - gitleaks detect --verbose --source . --report-format json --report-path gitleaks-report.json
  artifacts:
    reports:
      # GitLab can parse this for security dashboard
      secret_detection: gitleaks-report.json
    paths:
      - gitleaks-report.json
    when: always
    expire_in: 1 week

notify_alert_failure:
  stage: notify
  image: curlimages/curl:8.18.0
  script:
    - export SECRET_COUNT=$(cat gitleaks-report.json | grep -o '"Description":' | wc -l || echo "0")
    - |
      curl -X POST "${GOTIFY_NOTIFICATION_URL}" \
        -F "title=🚨 *SECURITY ALERT: SECRETS DETECTED!* 🚨" \
        -F "message=Project: ${CI_PROJECT_NAME}\nBranch: ${CI_COMMIT_REF_NAME}\nSecrets Found: ${SECRET_COUNT}\nCommit: ${CI_COMMIT_SHORT_SHA}\nAuthor: ${GITLAB_USER_NAME}\nPipeline: ${CI_PIPELINE_URL}" \
        -F "priority=10"
  dependencies:
    - gitleaks_scan
  when: on_failure

gradle_test:
  stage: test
  image: gradle:9.3.1-noble
  script:
    - gradle test