stages:
  - security
  - test
  - build

# My current work doesn't support docker tls.
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

gitleaks_scan:
  tags:
    - $RUNNER_TAG
  stage: security
  image: zricethezav/gitleaks:v8.30.0
  variables:
    GIT_DEPTH: 0
  script:
    - gitleaks detect --verbose --source . --report-format json --report-path gitleaks-report.json
  artifacts:
    reports:
      # GitLab can parse this for security dashboard
      secret_detection: gitleaks-report.json
    paths:
      - gitleaks-report.json
    when: always
    expire_in: 1 week

gradle_lint:
  tags:
    - $RUNNER_TAG
  stage: test
  image: gradle:9.5.0-jdk21-noble
  script:
    - gradle spotlessCheck

gradle_test:
  tags:
    - $RUNNER_TAG
  stage: test
  image: gradle:9.5.0-jdk21-noble
  script:
    - gradle test

gradle_integration_test:
  tags:
    - $RUNNER_TAG
  stage: test
  image: gradle:9.5.0-jdk21-noble
  services:
    - docker:29.1.3-dind
  before_script:
    - apt update && apt install -y ffmpeg
  script:
    - gradle integrationTest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.docker_build:
  tags:
    - $RUNNER_TAG
  stage: build
  image: docker:29.1.3
  services:
    - docker:29.1.3-dind
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build_scheduler_image:
  extends: .docker_build
  script:
    - docker build
        -f adapter_driving_scheduler_spring/Dockerfile
        -t "$CI_REGISTRY_IMAGE/scheduler:$CI_COMMIT_TAG"
        .
    - docker push "$CI_REGISTRY_IMAGE/scheduler:$CI_COMMIT_TAG"

build_runner_ffmpeg_image:
  extends: .docker_build
  script:
    - docker build
        -f adapter_driving_runner_spring/Dockerfile
        --build-arg TASK_IMPLS="task_impl_ffmpeg"
        --build-arg INCLUDE_FFMPEG=true
        -t "$CI_REGISTRY_IMAGE/runner-ffmpeg:$CI_COMMIT_TAG"
        .
    - docker push "$CI_REGISTRY_IMAGE/runner-ffmpeg:$CI_COMMIT_TAG"

build_runner_tasks_image:
  extends: .docker_build
  script:
    - docker build
        -f adapter_driving_runner_spring/Dockerfile
        --build-arg TASK_IMPLS="task_impl_http_fetch task_impl_llm_summarise task_impl_llm_translate task_impl_whisper_transcription"
        -t "$CI_REGISTRY_IMAGE/runner-tasks:$CI_COMMIT_TAG"
        .
    - docker push "$CI_REGISTRY_IMAGE/runner-tasks:$CI_COMMIT_TAG"