### @title Get job list no skipping or limiting
POST {{v1Url}}/teg/schedule
X-Auth-Principal: "test-user"
X-Auth-Roles: "admin,other-role"
Content-Type: application/json

{
  "tasks": [
    {
      "name": "it-should-run",
      "implementationName": "DemoEchoTask",
      "inputs": [
        {
          "name": "finally-awake.mp4",
          "type": "FILE"
        },
        {
          "name": "other-values",
          "type": "STRING_VALUE"
        }
      ],
      "outputs": [
        {
          "name": "finally-awake.mp4-processed",
          "type": "FILE"
        },
        {
          "name": "other-values-processed",
          "type": "STRING_VALUE"
        }
      ],
      "arguments": [
        "one",
        "two"
      ],
      "timeout": {
        "amount": 20,
        "temporalUnit": "SECONDS"
      }
    }
  ],
  "initArtefacts": [
    {
      "name": "finally-awake.mp4",
      "type": "FILE",
      "ref": "dd5fa300-77f2-4e4c-aeaa-d1f3de0eca22",
      "storedWith": "s3"
    },
    {
      "name": "other-values",
      "type": "STRING_VALUE",
      "value": "one,two"
    }
  ]
}