### @title Get job list no skipping or limiting
POST {{v1Url}}/teg/schedule
X-Auth-Principal: "test-user"
X-Auth-Roles: "admin"
Content-Type: application/json

{
  "tasks": [
    {
      "name": "convert to mp3",
      "implementationName": "FFMPEGTask",
      "inputs": [
        {
          "name": "finally-awake.mp4",
          "type": "FILE"
        }
      ],
      "outputs": [
        {
          "name": "finally-awake.mp3",
          "type": "FILE"
        }
      ],
      "arguments": [
        "-i finally-awake.mp4 -vn -acodec libmp3lame finally-awake.mp3",
        "30"
      ],
      "timeout": {
        "amount": 50,
        "temporalUnit": "SECONDS"
      }
    },
    {
        "name": "convert to text",
        "implementationName": "WhisperTranscriptionTask",
        "inputs": [
            {
            "name": "finally-awake.mp3",
            "type": "FILE"
            }
        ],
        "outputs": [
            {
            "name": "transcription.txt",
            "type": "FILE"
            }
        ],
        "arguments": [
          "transcription.txt"
        ],
        "timeout": {
            "amount": 300,
            "temporalUnit": "SECONDS"
        }
    }
  ],
  "initArtefacts": [
    {
      "name": "finally-awake.mp4",
      "type": "FILE",
      "ref": "b6f7dcca-6de8-45f6-91c9-1cf8c0b83ada",
      "storedWith": "s3"
    }
  ]
}