/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-task-plugin-conventions")
}

dependencies {
    testImplementation(project(":task_handler_test_support"))
}
