/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
    implementation(libs.kotlin.gradle.plugin)
    implementation(libs.org.jetbrains.kotlin.plugin.spring)
    implementation(libs.org.springframework.boot.gradle.plugin)
    implementation(libs.io.spring.dependency.management.plugin)
    implementation(libs.sentry.plugin)

    implementation(libs.gradle.test.logger.plugin)
}
